[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eNMRpy"
version = "0.0.6b"
description = "nmrglue-based package for the import and analysis of electrophoretic NMR-data"
readme = "README.md"
license = { file = "LICENSE.txt" }
authors = [
    { name = "Florian Ackermann", email = "nairolf.ackermann@gmail.com" },
]
dependencies = [
    "nmrglue",
    "lmfit>=1.0.1",
    "pandas",
    "matplotlib>=3.1.3",
    "numpy",
    "scipy",
    "scikit-learn",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pytest-xdist",
]
dev = [
    "eNMRpy[test]",
    "tox",
]

[project.urls]
Homepage = "https://github.com/Flackermann/eNMRpy/"

[tool.setuptools]
packages = ["eNMRpy", "eNMRpy.Measurement"]

[tool.pytest.ini_options]
testpaths = ["tests"]
